version: '3'
services:
  openapi-generator:
    image: openapitools/openapi-generator-cli:v5.3.1
    container_name: dart-openapi-generator
    volumes:
      - ./:/workspace
  swagger-api:
    image: stoplight/prism:3
    container_name: swagger-api
    ports:
      - "8082:4010"
    command: mock -d -h 0.0.0.0 /openapi.yml
    volumes:
      - ./openapi/generated/openapi/openapi.yaml:/openapi.yml